/*
 * Plugwerk — Plugin Marketplace for the PF4J Ecosystem
 * Copyright (C) 2026 devtank42 GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.annotations.UpdateTimestamp
import org.hibernate.annotations.UuidGenerator
import org.hibernate.type.SqlTypes
import java.time.OffsetDateTime
import java.util.UUID

/**
 * JPA entity representing a namespace in the Plugwerk system.
 *
 * A namespace is the top-level organisational unit in the Plugwerk data model. It groups
 * all plugins of an organisation or product under a unique [slug] and acts as the tenancy
 * boundary for the entire plugin catalogue.
 *
 * **Data model:** Each namespace maps to one row in the `namespace` table.
 * All child resources ([PluginEntity], [ApiKeyEntity]) reference exactly one namespace
 * via foreign key.
 *
 * **Usage:**
 * - Persisted and queried via [io.plugwerk.server.repository.NamespaceRepository].
 * - Managed (CRUD) by [io.plugwerk.server.service.NamespaceService].
 * - All API endpoints are namespace-scoped under `/api/v1/namespaces/{slug}/...`.
 *
 * @property id Primary key, UUIDv7 (time-based, generated by Hibernate).
 * @property slug URL-friendly unique identifier of the namespace (e.g. `acme-corp`).
 * @property ownerOrg Name of the owning organisation.
 * @property settings Optional namespace-specific configuration stored as a JSON object.
 * @property createdAt Creation timestamp (set automatically, immutable).
 * @property updatedAt Timestamp of the last modification (updated automatically).
 */
@Entity
@Table(name = "namespace")
class NamespaceEntity(
    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", updatable = false)
    var id: UUID? = null,

    @Column(name = "slug", nullable = false, unique = true, length = 255)
    var slug: String,

    @Column(name = "owner_org", nullable = false, length = 255)
    var ownerOrg: String,

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "settings")
    var settings: String? = null,

    @Column(name = "public_catalog", nullable = false)
    var publicCatalog: Boolean = false,

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    var updatedAt: OffsetDateTime = OffsetDateTime.now(),
)
