/*
 * Copyright (c) 2025-present devtank42 GmbH
 *
 * This file is part of Plugwerk.
 *
 * Plugwerk is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Plugwerk is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Plugwerk. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import jakarta.persistence.UniqueConstraint
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UuidGenerator
import java.time.OffsetDateTime
import java.util.UUID

/**
 * JPA entity representing an API key for authenticating against the Plugwerk server.
 *
 * API keys are the primary authentication method in Phase 1 (MVP). They grant access to
 * the API of a specific [NamespaceEntity] and are used for operations such as uploading
 * new plugin releases.
 *
 * **Security note:** The API key is **never stored in plain text**.
 * Only its SHA-256 hash ([keyHash]) is persisted. The original key is returned to the
 * caller exactly once at creation time and cannot be recovered afterwards.
 *
 * **Data model:** Each API key maps to one row in the `namespace_access_key` table.
 * The [keyHash] is unique (Unique Constraint). An API key belongs to exactly one
 * [NamespaceEntity].
 *
 * **Usage:**
 * - Persisted and queried via [io.plugwerk.server.repository.NamespaceAccessKeyRepository].
 * - Incoming requests are authenticated by hashing the submitted key and comparing it
 *   against the stored [keyHash].
 * - Keys can be disabled via [revoked] without deleting them, preserving the audit trail.
 * - The optional [expiresAt] field enables time-limited keys.
 *
 * @property id Primary key, UUIDv7 (time-based, generated by Hibernate).
 * @property namespace The [NamespaceEntity] this key grants access to (lazy-loaded).
 * @property keyHash SHA-256 hash of the API key (hex-encoded, 64 chars).
 *   Compared against incoming requests for authentication.
 * @property name Optional human-readable name to identify the key
 *   (e.g. `CI/CD Pipeline`).
 * @property revoked `true` if the key has been manually revoked and no longer permits
 *   authentication.
 * @property expiresAt Optional expiry timestamp. After this point the key is treated as
 *   invalid even if [revoked] is `false`.
 * @property createdAt Creation timestamp (set automatically, immutable).
 */
@Entity
@Table(
    name = "namespace_access_key",
    uniqueConstraints = [UniqueConstraint(columnNames = ["namespace_id", "name"])],
)
class NamespaceAccessKeyEntity(
    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", updatable = false)
    var id: UUID? = null,

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "namespace_id", nullable = false, updatable = false)
    var namespace: NamespaceEntity,

    @Column(name = "key_hash", nullable = false, unique = true, length = 64)
    var keyHash: String,

    @Column(name = "name", nullable = false, length = 255)
    var name: String,

    @Column(name = "revoked", nullable = false)
    var revoked: Boolean = false,

    @Column(name = "expires_at")
    var expiresAt: OffsetDateTime? = null,

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),
)
