/*
 * Plugwerk — Plugin Marketplace for the PF4J Ecosystem
 * Copyright (C) 2026 devtank42 GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.domain

import io.plugwerk.spi.model.ReleaseStatus
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.FetchType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import jakarta.persistence.UniqueConstraint
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.annotations.UpdateTimestamp
import org.hibernate.annotations.UuidGenerator
import org.hibernate.type.SqlTypes
import java.time.OffsetDateTime
import java.util.UUID

/**
 * JPA entity representing a versioned release of a plugin.
 *
 * A plugin release is a concrete, publishable version of a [PluginEntity]. It binds a
 * SemVer version number to a stored artefact (JAR or ZIP) and carries all metadata
 * required for installation, compatibility checks, and dependency resolution.
 *
 * **Data model:** Each release maps to one row in the `plugin_release` table.
 * The combination of `plugin_id` and `version` is unique (Unique Constraint).
 * A release belongs to exactly one [PluginEntity].
 *
 * **Lifecycle:**
 * New releases start in `DRAFT` status and progress through the following states
 * ([io.plugwerk.spi.model.ReleaseStatus]):
 * ```
 * DRAFT → PUBLISHED → DEPRECATED
 *                   → YANKED
 * ```
 * Only `PUBLISHED` releases are shown in the catalogue and considered for update checks.
 *
 * **Usage:**
 * - Persisted and queried via [io.plugwerk.server.repository.PluginReleaseRepository].
 * - Created by [io.plugwerk.server.service.PluginReleaseService] on artefact upload:
 *   the SHA-256 checksum and artefact key are computed and stored at upload time.
 * - [io.plugwerk.server.service.UpdateCheckService] compares installed versions against
 *   the latest `PUBLISHED` release using SemVer comparison.
 * - [io.plugwerk.server.service.Pf4jCompatibilityService] maps `PUBLISHED` releases to
 *   the pf4j-update format (`plugins.json`), including the download URL.
 *
 * @property id Primary key, UUIDv7 (time-based, generated by Hibernate).
 * @property plugin The associated [PluginEntity] (lazy-loaded).
 * @property version SemVer version number of this release (e.g. `1.2.3`).
 * @property artifactSha256 SHA-256 checksum of the stored artefact (hex-encoded, 64 chars).
 *   Computed at upload time and used for integrity verification on download.
 * @property artifactKey Storage-agnostic key for the artefact in the configured storage
 *   backend (e.g. `acme/my-plugin/1.2.3` for filesystem or S3).
 *   Interpreted by [io.plugwerk.server.service.storage.ArtifactStorageService],
 *   independent of the concrete storage type.
 * @property artifactSize Size of the stored artefact in bytes. Set at upload time from
 *   the raw byte array length. Exposed to clients for display purposes.
 * @property requiresSystemVersion Optional SemVer range for the minimum/maximum version
 *   of the host system (e.g. `>=2.0.0 & <4.0.0`).
 * @property pluginDependencies Optional list of plugin-to-plugin dependencies as a JSON
 *   array (e.g. `[{"id":"other-plugin","version":">=1.0.0"}]`).
 * @property status Current lifecycle status of the release
 *   (default: [io.plugwerk.spi.model.ReleaseStatus.DRAFT]).
 * @property createdAt Creation timestamp (set automatically, immutable).
 * @property updatedAt Timestamp of the last modification (updated automatically).
 */
@Entity
@Table(
    name = "plugin_release",
    uniqueConstraints = [UniqueConstraint(columnNames = ["plugin_id", "version"])],
)
class PluginReleaseEntity(
    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", updatable = false)
    var id: UUID? = null,

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "plugin_id", nullable = false, updatable = false)
    var plugin: PluginEntity,

    @Column(name = "version", nullable = false, length = 100)
    var version: String,

    @Column(name = "artifact_sha256", nullable = false, length = 64)
    var artifactSha256: String,

    @Column(name = "artifact_key", nullable = false, length = 1024)
    var artifactKey: String,

    @Column(name = "artifact_size", nullable = false)
    var artifactSize: Long = 0,

    @Column(name = "requires_system_version", length = 255)
    var requiresSystemVersion: String? = null,

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "plugin_dependencies")
    var pluginDependencies: String? = null,

    @Column(name = "download_count", nullable = false)
    var downloadCount: Long = 0,

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    var status: ReleaseStatus = ReleaseStatus.DRAFT,

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    var updatedAt: OffsetDateTime = OffsetDateTime.now(),
)
