/*
 * Copyright (c) 2025-present devtank42 GmbH
 *
 * This file is part of Plugwerk.
 *
 * Plugwerk is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Plugwerk is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Plugwerk. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.domain

import io.plugwerk.spi.model.PluginStatus
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.FetchType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import jakarta.persistence.UniqueConstraint
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.annotations.OnDelete
import org.hibernate.annotations.OnDeleteAction
import org.hibernate.annotations.UpdateTimestamp
import org.hibernate.annotations.UuidGenerator
import org.hibernate.type.SqlTypes
import java.time.OffsetDateTime
import java.util.UUID

/**
 * JPA entity representing a plugin entry in a namespace catalogue.
 *
 * A plugin is a registered PF4J plugin within a [NamespaceEntity]. It holds all metadata
 * relevant for discoverability in the catalogue (name, description, tags, etc.)
 * but contains no executable code itself — that lives in the associated [PluginReleaseEntity]
 * records as versioned artefacts.
 *
 * **Data model:** Each plugin entry maps to one row in the `plugin` table.
 * The combination of `namespace_id` and `plugin_id` is unique (Unique Constraint).
 * A plugin belongs to exactly one [NamespaceEntity] and may have any number of
 * [PluginReleaseEntity] entries.
 *
 * **Usage:**
 * - Persisted and queried via [io.plugwerk.server.repository.PluginRepository].
 * - Managed (CRUD and catalogue queries with optional status filter) by
 *   [io.plugwerk.server.service.PluginService].
 * - Created automatically by [io.plugwerk.server.service.PluginReleaseService] on
 *   artefact upload when no entry for the plugin identifier exists yet.
 * - Mapped to the pf4j-update format (`plugins.json`) by
 *   [io.plugwerk.server.service.Pf4jCompatibilityService] for active plugins.
 *
 * @property id Primary key, UUIDv7 (time-based, generated by Hibernate).
 * @property namespace The parent [NamespaceEntity] (lazy-loaded).
 * @property pluginId Business identifier of the plugin within the namespace
 *   (matches the PF4J plugin ID, e.g. `my-awesome-plugin`).
 * @property name Display name of the plugin.
 * @property description Long-form description (optional, free text).
 * @property provider Name of the plugin provider or organisation (optional).
 * @property license SPDX licence identifier of the plugin (optional, e.g. `Apache-2.0`).
 * @property homepage URL to the project homepage (optional).
 * @property repository URL to the source-code repository (optional).
 * @property icon URL to an icon image for catalogue display (optional).
 * @property tags Free-text list of keywords for catalogue search.
 * @property status Lifecycle status of the plugin ([io.plugwerk.spi.model.PluginStatus]):
 *   `ACTIVE` (published), `SUSPENDED` (blocked), or `ARCHIVED` (retired).
 * @property createdAt Creation timestamp (set automatically, immutable).
 * @property updatedAt Timestamp of the last modification (updated automatically).
 */
@Entity
@Table(
    name = "plugin",
    uniqueConstraints = [UniqueConstraint(columnNames = ["namespace_id", "plugin_id"])],
)
class PluginEntity(
    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", updatable = false)
    var id: UUID? = null,

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "namespace_id", nullable = false, updatable = false)
    @OnDelete(action = OnDeleteAction.CASCADE)
    var namespace: NamespaceEntity,

    @Column(name = "plugin_id", nullable = false, length = 255)
    var pluginId: String,

    @Column(name = "name", nullable = false, length = 255)
    var name: String,

    @Column(name = "description", columnDefinition = "text")
    var description: String? = null,

    @Column(name = "provider", length = 255)
    var provider: String? = null,

    @Column(name = "license", length = 100)
    var license: String? = null,

    @Column(name = "homepage", length = 2048)
    var homepage: String? = null,

    @Column(name = "repository", length = 2048)
    var repository: String? = null,

    @Column(name = "icon", length = 2048)
    var icon: String? = null,

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "tags", nullable = false)
    var tags: Array<String> = emptyArray(),

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    var status: PluginStatus = PluginStatus.ACTIVE,

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    var updatedAt: OffsetDateTime = OffsetDateTime.now(),
)
