/*
 * Copyright (c) 2025-present devtank42 GmbH
 *
 * This file is part of Plugwerk.
 *
 * Plugwerk is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Plugwerk is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Plugwerk. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.annotations.UuidGenerator
import java.time.OffsetDateTime
import java.util.UUID

/**
 * Server-side record backing the opaque refresh cookie (ADR-0027, issue #294).
 *
 * Only the HMAC-SHA256 of the plaintext refresh token is stored ([tokenLookupHash]) — the
 * plaintext lives exactly once in the `Set-Cookie` response header and never touches disk.
 * Lookup uses a unique-index equality probe, matching the constant-time pattern from
 * ADR-0024 (namespace-access-key HMAC lookup).
 *
 * Rotation: every successful `/api/v1/auth/refresh` revokes this row (sets [revokedAt] +
 * [revocationReason] = `ROTATED`) and issues a successor, linked via [rotatedToId].
 *
 * Reuse detection: if a revoked row is presented again, the entire [familyId] group is
 * revoked with reason `REUSE_DETECTED` — the classic refresh-token reuse defence.
 *
 * **Revocation reasons** (stored as lowercase strings; kept as `varchar(32)` rather than
 * an enum table for deliberate simplicity):
 * - `ROTATED` — normal rotation during refresh.
 * - `LOGOUT` — user-initiated logout or password change.
 * - `REUSE_DETECTED` — a revoked token was replayed; family force-revoked.
 * - `ADMIN_REVOKE` — operator-initiated revocation.
 * - `EXPIRED_CLEANUP` — scheduled cleanup marker (retained briefly for audit).
 *
 * @property id Primary key, UUIDv7 (time-based, generated by Hibernate).
 * @property familyId Session family — every token rotated within one login groups here.
 * @property userId Foreign key to `plugwerk_user(id)`. `ON DELETE CASCADE`: refresh tokens
 *   do not outlive their owning user.
 * @property tokenLookupHash Hex-encoded HMAC-SHA256(jwtSecret, plaintextToken) — 64 chars.
 * @property issuedAt When the token was minted (default `now()` via DB).
 * @property expiresAt Absolute expiry. After this instant the row is eligible for cleanup.
 * @property revokedAt When the token was revoked, if ever. Null for active tokens.
 * @property revocationReason Machine-readable reason enum; see class-level KDoc.
 * @property rotatedToId Successor row (non-null when this token was rotated forward),
 *   self-referencing FK with `ON DELETE SET NULL` so chain deletes do not cascade.
 * @property upstreamIdToken Raw upstream OIDC `id_token` value, captured at OIDC login
 *   time and copied forward across rotations. Used as `id_token_hint` for RP-Initiated
 *   Logout against the IdP's `end_session_endpoint` (#352). Null for local-login rows
 *   and for OIDC providers that never returned an ID token. Never logged or returned
 *   to API clients.
 */
@Entity
@Table(name = "refresh_token")
class RefreshTokenEntity(
    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", updatable = false)
    var id: UUID? = null,

    @Column(name = "family_id", nullable = false, updatable = false)
    var familyId: UUID,

    @Column(name = "user_id", nullable = false, updatable = false)
    var userId: UUID,

    @Column(name = "token_lookup_hash", nullable = false, unique = true, length = 64, updatable = false)
    var tokenLookupHash: String,

    @Column(name = "issued_at", nullable = false, updatable = false)
    var issuedAt: OffsetDateTime = OffsetDateTime.now(),

    @Column(name = "expires_at", nullable = false, updatable = false)
    var expiresAt: OffsetDateTime,

    @Column(name = "revoked_at")
    var revokedAt: OffsetDateTime? = null,

    @Column(name = "revocation_reason", length = 32)
    var revocationReason: String? = null,

    @Column(name = "rotated_to_id")
    var rotatedToId: UUID? = null,

    @Column(name = "upstream_id_token", columnDefinition = "TEXT")
    var upstreamIdToken: String? = null,
)
