/*
 * Copyright (c) 2025-present devtank42 GmbH
 *
 * This file is part of Plugwerk.
 *
 * Plugwerk is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Plugwerk is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Plugwerk. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UuidGenerator
import java.time.OffsetDateTime
import java.util.UUID

/**
 * JPA entity representing a revoked JWT token.
 *
 * When a user logs out or their password is changed, the SHA-256 hash of the token's
 * [jti] claim is stored here so the [io.plugwerk.server.security.DelegatingJwtDecoder]
 * can reject the token before expiry. Expired entries are cleaned up by a scheduled job.
 *
 * **Hashed at rest (SBS-013 / #268):** the column stores hex-encoded
 * SHA-256(jti) — never the raw JWT ID. The check path only ever needs to ask
 * "have I seen this jti before?", which is fully answerable from a digest.
 * A database leak therefore exposes opaque hashes instead of valid token IDs.
 * Hashing is performed in
 * [io.plugwerk.server.service.TokenRevocationService.revokeToken] /
 * [io.plugwerk.server.service.TokenRevocationService.isRevoked]; never construct
 * this entity with a raw JTI from outside that service.
 *
 * @property id Primary key, UUIDv7 (time-based, generated by Hibernate).
 * @property jti Hex-encoded SHA-256 of the JWT `jti` claim (64 characters).
 *   Unique. The column name is kept for stability; the value is a hash.
 * @property username The subject of the revoked token, for audit purposes.
 * @property expiresAt Original expiry time of the token. Used by the cleanup job to purge
 *   entries that are no longer relevant (the token would have expired anyway).
 * @property revokedAt Timestamp when the token was revoked (set automatically).
 */
@Entity
@Table(name = "revoked_token")
class RevokedTokenEntity(
    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", updatable = false)
    var id: UUID? = null,

    @Column(name = "jti", nullable = false, unique = true, length = 64)
    var jti: String,

    @Column(name = "username", nullable = false, length = 255)
    var username: String,

    @Column(name = "expires_at", nullable = false)
    var expiresAt: OffsetDateTime,

    @CreationTimestamp
    @Column(name = "revoked_at", nullable = false, updatable = false)
    var revokedAt: OffsetDateTime = OffsetDateTime.now(),
)
