/*
 * Copyright (c) 2025-present devtank42 GmbH
 *
 * This file is part of Plugwerk.
 *
 * Plugwerk is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Plugwerk is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Plugwerk. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp
import org.hibernate.annotations.UuidGenerator
import java.time.OffsetDateTime
import java.util.UUID

/**
 * JPA entity representing a local Plugwerk user.
 *
 * Local users authenticate via username/password (BCrypt-hashed). They are distinct from
 * OIDC-sourced identities, which are referenced only by their [user_subject] claim in
 * [NamespaceMemberEntity] without a corresponding row here.
 *
 * **Security note:** [passwordHash] stores a BCrypt hash — the plain-text password is never
 * persisted. On first login after creation, [passwordChangeRequired] is `true`, forcing the
 * user to set a new password before accessing any resource.
 *
 * **Data model:** Maps to the `plugwerk_user` table. (`user` is a reserved word in PostgreSQL.)
 *
 * @property id Primary key, UUIDv7 (time-based, generated by Hibernate).
 * @property username Unique login name.
 * @property email Optional email address (unique when set).
 * @property passwordHash BCrypt hash of the user's password.
 * @property enabled Whether the user account is active. Disabled users cannot log in.
 * @property passwordChangeRequired When `true`, the user must change their password on next login.
 *   Set to `true` by default so that admin-created accounts force a password reset on first use.
 * @property createdAt Creation timestamp (set automatically, immutable).
 * @property updatedAt Timestamp of the last modification (updated automatically).
 */
@Entity
@Table(name = "plugwerk_user")
class UserEntity(
    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", updatable = false)
    var id: UUID? = null,

    @Column(name = "username", nullable = false, unique = true, length = 255)
    var username: String,

    @Column(name = "email", unique = true, length = 255)
    var email: String? = null,

    @Column(name = "password_hash", nullable = false, length = 255)
    var passwordHash: String,

    @Column(name = "enabled", nullable = false)
    var enabled: Boolean = true,

    @Column(name = "password_change_required", nullable = false)
    var passwordChangeRequired: Boolean = true,

    @Column(name = "is_superadmin", nullable = false)
    var isSuperadmin: Boolean = false,

    @Column(name = "password_invalidated_before")
    var passwordInvalidatedBefore: OffsetDateTime? = null,

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    var updatedAt: OffsetDateTime = OffsetDateTime.now(),
)
