/*
 * Copyright (c) 2025-present devtank42 GmbH
 *
 * This file is part of Plugwerk.
 *
 * Plugwerk is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Plugwerk is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Plugwerk. If not, see <https://www.gnu.org/licenses/>.
 */
package io.plugwerk.server.service

import org.springframework.boot.info.BuildProperties
import org.springframework.stereotype.Component

/**
 * Provides the application version using a fallback chain:
 *
 * 1. [BuildProperties.getVersion] — from `META-INF/build-info.properties` (generated by
 *    `springBoot { buildInfo() }` in `build.gradle.kts`)
 * 2. JAR manifest `Implementation-Version` attribute
 * 3. `"unknown"` as last resort
 */
@Component
class VersionProvider(private val buildProperties: BuildProperties?) {

    fun getVersion(): String = buildProperties?.version
        ?: javaClass.`package`?.implementationVersion
        ?: "unknown"
}
